### ISSUE TITLE
How to use GroupManager ranks?

### ISSUE THREAD

**Issue by Zilacon** [ProxyConn/UntamedChat#6]
Hello id like to use your plugin on my bungee server but it removes the format for my ranks setup on GroupManager.

Is there a way to set it up so it is like {server} {gmprefix}{player}{gmsuffix}?

**Comment by portalBlock** [comment]
Currently this is not possible.

**Comment by Zilacon** [comment]
For those who are sick of lazy programmers who close issues/suggestions like this cause they dont feel like improving anything go here: http://dev.bukkit.org/bukkit-plugins/bungeechatplus/

Much better alternative, and the author actually gives a shit.

**Comment by Wferr** [comment]
@Zilacon this is impossible currently with how UntamedChat is setup, it works on a bungee level and not on a spigot/bukkit level.

**Comment by Zilacon** [comment]
Sounds like a personal problem. BungeeChatPlus simply works as a bukkit bridge and bungee plugin. I think you need to work harder on your excuses.

**Comment by Wferr** [comment]
Sure looks like you having a good time with that plugin 

![](http://i.imgur.com/Bg6md5C.png)

**Comment by Zilacon** [comment]
Its a compatibility issue with https://github.com/Poweruser/MinetickMod/tree/v1.7.10
Its built for bukkit/spigot which KCauldron is also built off of and works great on there. But MineTick is a completely different story which is what we run on our HUB.

The author already got on our teamspeak and our server to check things out and hes working on a fix.

**Comment by Wferr** [comment]
Congrats, hope that works out for you! Have fun with that plugin, and thanks for stopping by!
